"""
Face Authentication Module
----------------------------
Reuses the encodings.pickle generated by the earlier face-recognition
project. Instead of running a continuous live-recognition loop, this
module performs a single authentication check: it opens the webcam,
tries to match a face against known encodings within a time limit,
and returns the matched person's name (or None if no match/timeout).

This is meant to be imported and called from main.py, not run directly
(though a __main__ block is included for standalone testing).
"""

import os
import pickle
import time

import cv2
import face_recognition
import numpy as np


class FaceAuthError(Exception):
    """Raised when authentication cannot proceed (e.g. missing encodings file)."""
    pass


def load_known_encodings(encodings_path):
    if not os.path.exists(encodings_path):
        raise FaceAuthError(
            f"Encodings file not found at '{encodings_path}'. "
            "Copy encodings.pickle from your face-recognition project, "
            "or run register_faces.py + encode_faces.py first."
        )
    with open(encodings_path, "rb") as f:
        data = pickle.load(f)
    if not data.get("encodings"):
        raise FaceAuthError(
            "Encodings file is empty. Register at least one person before authenticating."
        )
    return data["encodings"], data["names"]


def authenticate_user(encodings_path="encodings.pickle", timeout_seconds=10, tolerance=0.6):
    """
    Attempts to authenticate a user via webcam within timeout_seconds.

    Returns:
        str: the matched person's name, if authentication succeeds
        None: if no match was found before the timeout, or no face was
              detected at all
    """
    known_encodings, known_names = load_known_encodings(encodings_path)

    cap = cv2.VideoCapture(0)
    if not cap.isOpened():
        raise FaceAuthError("Could not access the webcam. Check it's connected and not in use.")

    print("Authenticating... please look at the camera.")
    start_time = time.time()
    matched_name = None

    try:
        while time.time() - start_time < timeout_seconds:
            success, frame = cap.read()
            if not success:
                continue

            frame = cv2.flip(frame, 1)
            small_frame = cv2.resize(frame, (0, 0), fx=0.25, fy=0.25)
            rgb_small_frame = cv2.cvtColor(small_frame, cv2.COLOR_BGR2RGB)

            face_locations = face_recognition.face_locations(rgb_small_frame)
            face_encodings = face_recognition.face_encodings(rgb_small_frame, face_locations)

            for face_encoding in face_encodings:
                matches = face_recognition.compare_faces(
                    known_encodings, face_encoding, tolerance=tolerance
                )
                if True in matches:
                    face_distances = face_recognition.face_distance(known_encodings, face_encoding)
                    best_match_index = np.argmin(face_distances)
                    if matches[best_match_index]:
                        matched_name = known_names[best_match_index]
                        break

            # Show live feedback window during authentication
            status_text = f"Matched: {matched_name}" if matched_name else "Scanning..."
            cv2.putText(
                frame, status_text, (10, 30),
                cv2.FONT_HERSHEY_SIMPLEX, 0.8,
                (0, 255, 0) if matched_name else (0, 255, 255), 2,
            )
            cv2.imshow("Face Authentication", frame)
            cv2.waitKey(1)

            if matched_name:
                break
    finally:
        cap.release()
        cv2.destroyAllWindows()

    return matched_name


if __name__ == "__main__":
    # Standalone test: python face_auth.py
    result = authenticate_user(encodings_path="../encodings.pickle", timeout_seconds=10)
    if result:
        print(f"Authenticated as: {result}")
    else:
        print("Authentication failed: no known face detected in time.")